document.addEventListener('DOMContentLoaded', function() {
    const chatButton = document.getElementById('chat-button');
    const chatWindow = document.getElementById('chat-window');
    const chatInput = document.getElementById('chat-input');
    const chatMessages = document.getElementById('chat-messages');
    const themeToggle = document.getElementById('theme-toggle');
    const languageSelector = document.getElementById('language-selector');
    const body = document.body;

    chatButton.addEventListener('click', function() {
        chatWindow.classList.toggle('open');
    });

    chatInput.addEventListener('keypress', function(e) {
        if (e.key === 'Enter') {
            const userMessage = chatInput.value;
            if (userMessage.trim() !== '') {
                appendMessage('Usuário', userMessage);
                chatInput.value = '';
                const botResponse = generateResponse(userMessage, languageSelector.value);
                setTimeout(() => {
                    appendMessage('Bot', botResponse);
                }, 1000);
            }
        }
    });

    themeToggle.addEventListener('click', function() {
        body.classList.toggle('dark-theme');
    });

    languageSelector.addEventListener('change', function() {
        const selectedLanguage = languageSelector.value;
        changeLanguage(selectedLanguage);
    });

    function changeLanguage(language) {
        const elements = document.querySelectorAll('[data-lang]');
        elements.forEach(element => {
            const key = element.getAttribute('data-lang');
            element.textContent = translations[language][key];
        });
    }

    function appendMessage(sender, message) {
        const messageElement = document.createElement('div');
        messageElement.classList.add('message', sender.toLowerCase());
        messageElement.textContent = `${sender}: ${message}`;
        chatMessages.appendChild(messageElement);
        chatMessages.scrollTop = chatMessages.scrollHeight;
    }

    function generateResponse(userMessage, language) {
        const keywords = {
            pt: {
                hello: 'Olá! Sou seu assistente virtual. Estou aqui para ajudar com informações sobre doações de sangue e agendamentos. Como posso ajudar você hoje?',
                oi: 'Olá! Sou seu assistente virtual. Estou aqui para ajudar com informações sobre doações de sangue e agendamentos. Como posso ajudar você hoje?',
                bom_dia: 'Bom dia! Sou seu assistente virtual. Como posso ajudar você hoje?',
                boa_tarde: 'Boa tarde! Sou seu assistente virtual. Como posso ajudar você hoje?',
                boa_noite: 'Boa noite! Sou seu assistente virtual. Como posso ajudar você hoje?',
                tudo_bem: 'Estou aqui para ajudar! O que você gostaria de saber?',
                me_ajude: 'Claro! Estou aqui para ajudar. O que você precisa?',
                como_faco_isso: 'Para acessar a seção de agendamentos, clique no menu principal e selecione "Agendamento".',
                agendamento: 'Para agendar uma doação, clique na seção de agendamentos no menu principal. Você poderá escolher a data e a unidade de coleta de sua preferência.',
                donate: 'Para doar sangue, você pode agendar uma visita pelo nosso site.',
                agendar: 'Para agendar um exame, acesse a seção de agendamentos no nosso site.',
                como: 'Para acessar a seção de agendamentos, clique no menu principal e selecione "Agendamento".'
            },
            en: {
                hello: 'Hello! I am your virtual assistant. I am here to help with information about blood donations and scheduling. How can I assist you today?',
                hi: 'Hello! I am your virtual assistant. How can I assist you today?',
                good_morning: 'Good morning! How can I assist you today?',
                good_afternoon: 'Good afternoon! How can I assist you today?',
                good_evening: 'Good evening! How can I assist you today?',
                how_are_you: 'I am here to help! What would you like to know?',
                help_me: 'Of course! I am here to help. What do you need?',
                how_do_i_do_this: 'To access the scheduling section, click on the main menu and select "Scheduling".',
                agendamento: 'To schedule a donation, click on the scheduling section in the main menu. You can choose your preferred date and collection unit.',
                donate: 'To donate blood, you can schedule a visit through our website.',
                agendar: 'To schedule an exam, please visit the scheduling section on our website.',
                como: 'To access the scheduling section, click on the main menu and select "Scheduling".'
            },
            ja: {
                hello: 'こんにちは！ 私はあなたのバーチャルアシスタントです。今日はどのようにお手伝いできますか？',
                こんにちは: 'こんにちは！ 私はあなたのバーチャルアシスタントです。今日はどのようにお手伝いできますか？',
                おはよう: 'おはようございます！ 今日はどのようにお手伝いできますか？',
                こんにちは: 'こんにちは！ 今日はどのようにお手伝いできますか？',
                こんばんは: 'こんばんは！ 今日はどのようにお手伝いできますか？',
                元気ですか: 'お手伝いします！ 何を知りたいですか？',
                助けて: 'もちろん！ お手伝いします。何が必要ですか？',
                どうすればいいですか: '予約セクションにアクセスするには、メインメニューをクリックして「予約」を選択してください。',
                agendamento: '寄付を予約するには、メインメニューの予約セクションをクリックしてください。希望の日付と収集ユニットを選択できます。',
                donate: '献血するには、私たちのウェブサイトから訪問を予約できます。',
                agendar: '検査を予約するには、ウェブサイトの予約セクションにアクセスしてください。',
                como: '予約セクションにアクセスするには、メインメニューをクリックして「予約」を選択してください。'
            },
            ru: {
                hello: 'Здравствуйте! Я ваш виртуальный помощник. Как я могу помочь вам сегодня?',
                привет: 'Здравствуйте! Я ваш виртуальный помощник. Как я могу помочь вам сегодня?',
                доброе_утро: 'Доброе утро! Как я могу помочь вам сегодня?',
                добрый_день: 'Добрый день! Как я могу помочь вам сегодня?',
                добрый_вечер: 'Добрый вечер! Как я могу помочь вам сегодня?',
                как_дела: 'Я здесь, чтобы помочь! Что бы вы хотели узнать?',
                помогите: 'Конечно! Я здесь, чтобы помочь. Что вам нужно?',
                как_это_сделать: 'Чтобы получить доступ к разделу расписания, нажмите на главное меню и выберите "Расписание".',
                agendamento: 'Чтобы запланировать пожертвование, нажмите на раздел расписания в главном меню. Вы можете выбрать предпочитаемую дату и единицу сбора.',
                donate: 'Чтобы сдать кровь, вы можете записаться на прием через наш сайт.',
                agendar: 'Чтобы записаться на экзамен, посетите раздел расписания на нашем сайте.',
                como: 'Чтобы получить доступ к разделу расписания, нажмите на главное меню и выберите "Расписание".'
            }
        };

        const lowerCaseMessage = userMessage.toLowerCase();
        for (const [keyword, response] of Object.entries(keywords[language])) {
            if (lowerCaseMessage.includes(keyword)) {
                return response;
            }
        }
        return translations[language]['defaultResponse'] || 'Desculpe, não entendi sua pergunta.';
    }

    const translations = {
        pt: {
            sobre: 'Sobre',
            comoDoar: 'Como Doar',
            requisitos: 'Requisitos',
            agendamento: 'Agendamento',
            campanhas: 'Campanhas',
            contato: 'Contato',
            heroTitle: 'Doe Sangue, Salve Vidas',
            heroDescription: 'Uma única doação pode salvar até 4 vidas. Seja um herói!',
            queroSerDoador: 'Quero ser Doador',
            agendarDoacao: 'Agendar Doação',
            sobreTitle: 'Sobre Nós',
            missao: 'Nossa Missão',
            missaoDescription: 'Conectamos doadores a quem mais precisa, salvando vidas através da doação de sangue.',
            impactoSocial: 'Impacto Social',
            impactoSocialDescription: 'Já ajudamos mais de 10.000 pessoas através de doações voluntárias.',
            estrutura: 'Estrutura',
            estruturaDescription: 'Contamos com 5 unidades de coleta e parceria com os principais hospitais.',
            comoDoarTitle: 'Como Funciona a Doação?',
            cadastro: 'Cadastro',
            cadastroDescription: 'Faça seu cadastro online ou em uma de nossas unidades',
            triagem: 'Triagem',
            triagemDescription: 'Avaliação rápida do seu estado de saúde',
            doacao: 'Doação',
            doacaoDescription: 'Processo seguro e supervisionado por profissionais',
            lanche: 'Lanche',
            lancheDescription: 'Recupere suas energias com um lanche especial',
            requisitosTitle: 'Requisitos para Doação',
            idade: 'Idade',
            idadeDescription: 'Entre 16 e 69 anos',
            peso: 'Peso',
            pesoDescription: 'Mínimo de 50kg',
            descanso: 'Descanso',
            descansoDescription: 'Boa noite de sono',
            alimentacao: 'Alimentação',
            alimentacaoDescription: 'Não estar em jejum',
            documentos: 'Documentos',
            documentosDescription: 'Documento oficial com foto',
            intervalo: 'Intervalo',
            intervaloDescription: '60 dias homens, 90 dias mulheres',
            agendamentoTitle: 'Agende sua Doação',
            campanhasTitle: 'Campanhas Ativas',
            precisamosDeO: 'Precisamos de O-',
            estoqueCritico: 'Estoque crítico! Sua doação é fundamental.',
            campanhaEmpresarial: 'Campanha Empresarial',
            campanhaEmpresarialDescription: 'Sua empresa pode fazer a diferença! Organize uma campanha de doação.',
            doeNoSeuAniversario: 'Doe no seu Aniversário',
            doeNoSeuAniversarioDescription: 'Comemore seu dia salvando vidas! Ganhe um brinde especial.',
            contatoTitle: 'Entre em Contato',
            telefone: 'Telefone',
            email: 'Email',
            enderecos: 'Endereços',
            envieSuaMensagem: 'Envie sua Mensagem',
            bancoDeSangue: 'Banco de Sangue',
            transformandoVidas: 'Transformando vidas através da solidariedade.',
            linksRapidos: 'Links Rápidos',
            horarioDeAtendimento: 'Horário de Atendimento',
            segundaASexta: 'Segunda a Sexta: 8h às 17h',
            sabado: 'Sábado: 8h às 12h',
            domingo: 'Domingo: Fechado',
            newsletter: 'Newsletter',
            recebaNovidades: 'Receba novidades e campanhas',
            politicaDePrivacidade: 'Política de Privacidade',
            termosDeUso: 'Termos de Uso',
            mapaDoSite: 'Mapa do Site',
            nomeLabel: 'Nome Completo',
            nomePlaceholder: 'Nome',
            dataLabel: 'Data Preferencial',
            unidadeLabel: 'Unidade de Coleta',
            selecioneUnidade: 'Selecione uma unidade',
            unidadeCentro: 'Unidade Centro',
            unidadeZonaSul: 'Unidade Zona Sul',
            unidadeZonaNorte: 'Unidade Zona Norte',
            periodoLabel: 'Período',
            selecionePeriodo: 'Selecione um período',
            periodoManha: 'Manhã (8h - 12h)',
            periodoTarde: 'Tarde (13h - 17h)',
            agendarBotao: 'Agendar Doação',
            defaultResponse: 'Desculpe, não entendi sua pergunta.'
        },
        en: {
            sobre: 'About',
            comoDoar: 'How to Donate',
            requisitos: 'Requirements',
            agendamento: 'Schedule',
            campanhas: 'Campaigns',
            contato: 'Contact',
            heroTitle: 'Donate Blood, Save Lives',
            heroDescription: 'A single donation can save up to 4 lives. Be a hero!',
            queroSerDoador: 'Want to Donate',
            agendarDoacao: 'Schedule Donation',
            sobreTitle: 'About Us',
            missao: 'Our Mission',
            missaoDescription: 'We connect donors with those in need, saving lives through blood donation.',
            impactoSocial: 'Social Impact',
            impactoSocialDescription: 'We have helped over 10,000 people through voluntary donations.',
            estrutura: 'Structure',
            estruturaDescription: 'We have 5 collection units and partnerships with major hospitals.',
            comoDoarTitle: 'How Donation Works?',
            cadastro: 'Registration',
            cadastroDescription: 'Register online or at one of our units',
            triagem: 'Screening',
            triagemDescription: 'Quick assessment of your health status',
            doacao: 'Donation',
            doacaoDescription: 'Safe process supervised by professionals',
            lanche: 'Snack',
            lancheDescription: 'Recharge your energy with a special snack',
            requisitosTitle: 'Donation Requirements',
            idade: 'Age',
            idadeDescription: 'Between 16 and 69 years',
            peso: 'Weight',
            pesoDescription: 'Minimum of 50kg',
            descanso: 'Rest',
            descansoDescription: 'Good night sleep',
            alimentacao: 'Food',
            alimentacaoDescription: 'Not fasting',
            documentos: 'Documents',
            documentosDescription: 'Official photo ID',
            intervalo: 'Interval',
            intervaloDescription: '60 days men, 90 days women',
            agendamentoTitle: 'Schedule Your Donation',
            campanhasTitle: 'Active Campaigns',
            precisamosDeO: 'We Need O-',
            estoqueCritico: 'Critical stock! Your donation is essential.',
            campanhaEmpresarial: 'Corporate Campaign',
            campanhaEmpresarialDescription: 'Your company can make a difference! Organize a donation campaign.',
            doeNoSeuAniversario: 'Donate on Your Birthday',
            doeNoSeuAniversarioDescription: 'Celebrate your day by saving lives! Get a special gift.',
            contatoTitle: 'Contact Us',
            telefone: 'Phone',
            email: 'Email',
            enderecos: 'Addresses',
            envieSuaMensagem: 'Send Your Message',
            bancoDeSangue: 'Blood Bank',
            transformandoVidas: 'Transforming lives through solidarity.',
            linksRapidos: 'Quick Links',
            horarioDeAtendimento: 'Opening Hours',
            segundaASexta: 'Monday to Friday: 8am to 5pm',
            sabado: 'Saturday: 8am to 12pm',
            domingo: 'Sunday: Closed',
            newsletter: 'Newsletter',
            recebaNovidades: 'Receive news and campaigns',
            politicaDePrivacidade: 'Privacy Policy',
            termosDeUso: 'Terms of Use',
            mapaDoSite: 'Site Map',
            nomeLabel: 'Full Name',
            nomePlaceholder: 'Name',
            dataLabel: 'Preferred Date',
            unidadeLabel: 'Collection Unit',
            selecioneUnidade: 'Select a unit',
            unidadeCentro: 'Center Unit',
            unidadeZonaSul: 'South Zone Unit',
            unidadeZonaNorte: 'North Zone Unit',
            periodoLabel: 'Period',
            selecionePeriodo: 'Select a period',
            periodoManha: 'Morning (8am - 12pm)',
            periodoTarde: 'Afternoon (1pm - 5pm)',
            agendarBotao: 'Schedule Donation',
            defaultResponse: 'Sorry, I did not understand your question.'
        },
        ja: {
            sobre: '約',
            comoDoar: '寄付方法',
            requisitos: '要件',
            agendamento: 'スケジュール',
            campanhas: 'キャンペーン',
            contato: '連絡先',
            heroTitle: '献血、命を救う',
            heroDescription: '1回の献血で最大4人の命を救うことができます。ヒーローになろう！',
            queroSerDoador: '寄付したい',
            agendarDoacao: '寄付を予約する',
            sobreTitle: '私たちについて',
            missao: '私たちの使命',
            missaoDescription: '私たちは、献血を通じて命を救うために、ドナーと必要としている人々を結びつけます。',
            impactoSocial: '社会的影響',
            impactoSocialDescription: '私たちは、ボランティア献血を通じて10,000人以上の人々を支援してきました。',
            estrutura: '構造',
            estruturaDescription: '私たちは5つの収集ユニットを持ち、主要な病院と提携しています。',
            comoDoarTitle: '寄付の仕組みは？',
            cadastro: '登録',
            cadastroDescription: 'オンラインまたは当社のユニットの1つで登録してください',
            triagem: 'スクリーニング',
            triagemDescription: 'あなたの健康状態の迅速な評価',
            doacao: '寄付',
            doacaoDescription: '専門家によって監督される安全なプロセス',
            lanche: 'スナック',
            lancheDescription: '特別なスナックでエネルギーを補充してください',
            requisitosTitle: '寄付の要件',
            idade: '年齢',
            idadeDescription: '16歳から69歳まで',
            peso: '重量',
            pesoDescription: '最低50kg',
            descanso: '休息',
            descansoDescription: '良い夜の睡眠',
            alimentacao: '食べ物',
            alimentacaoDescription: '断食していない',
            documentos: 'ドキュメント',
            documentosDescription: '公式の写真付きID',
            intervalo: '間隔',
            intervaloDescription: '男性60日、女性90日',
            agendamentoTitle: '寄付を予約する',
            campanhasTitle: 'アクティブなキャンペーン',
            precisamosDeO: 'O-が必要です',
            estoqueCritico: '重要な在庫！あなたの寄付は不可欠です。',
            campanhaEmpresarial: '企業キャンペーン',
            campanhaEmpresarialDescription: 'あなたの会社は違いを生むことができます！寄付キャンペーンを組織してください。',
            doeNoSeuAniversario: '誕生日に寄付する',
            doeNoSeuAniversarioDescription: '命を救うことであなたの日を祝ってください！特別なギフトを手に入れましょう。',
            contatoTitle: 'お問い合わせ',
            telefone: '電話',
            email: 'Eメール',
            enderecos: '住所',
            envieSuaMensagem: 'メッセージを送信する',
            bancoDeSangue: '血液銀行',
            transformandoVidas: '連帯を通じて命を変える。',
            linksRapidos: 'クイックリンク',
            horarioDeAtendimento: '営業時間',
            segundaASexta: '月曜日から金曜日：午前8時から午後5時まで',
            sabado: '土曜日：午前8時から午後12時まで',
            domingo: '日曜日：休業',
            newsletter: 'ニュースレター',
            recebaNovidades: 'ニュースとキャンペーンを受け取る',
            politicaDePrivacidade: 'プライバシーポリシー',
            termosDeUso: '利用規約',
            mapaDoSite: 'サイトマップ',
            nomeLabel: 'フルネーム',
            nomePlaceholder: '名前',
            dataLabel: '希望日',
            unidadeLabel: '収集ユニット',
            selecioneUnidade: 'ユニットを選択',
            unidadeCentro: 'センターユニット',
            unidadeZonaSul: '南ゾーンユニット',
            unidadeZonaNorte: '北ゾーンユニット',
            periodoLabel: '期間',
            selecionePeriodo: '期間を選択',
            periodoManha: '午前 (8時 - 12時)',
            periodoTarde: '午後 (13時 - 17時)',
            agendarBotao: '寄付を予約する',
            defaultResponse: 'すみません、あなたの質問がわかりませんでした。'
        },
        ru: {
            sobre: 'О нас',
            comoDoar: 'Как пожертвовать',
            requisitos: 'Требования',
            agendamento: 'Расписание',
            campanhas: 'Кампании',
            contato: 'Контакт',
            heroTitle: 'Донорство крови, спасение жизней',
            heroDescription: 'Одно пожертвование может спасти до 4 жизней. Будь героем!',
            queroSerDoador: 'Хочу пожертвовать',
            agendarDoacao: 'Запланировать пожертвование',
            sobreTitle: 'О нас',
            missao: 'Наша миссия',
            missaoDescription: 'Мы соединяем доноров с нуждающимися, спасая жизни через донорство крови.',
            impactoSocial: 'Социальное воздействие',
            impactoSocialDescription: 'Мы помогли более 10,000 человек через добровольные пожертвования.',
            estrutura: 'Структура',
            estruturaDescription: 'У нас есть 5 сборочных пунктов и партнерства с основными больницами.',
            comoDoarTitle: 'Как работает донорство?',
            cadastro: 'Регистрация',
            cadastroDescription: 'Зарегистрируйтесь онлайн или в одном из наших пунктов',
            triagem: 'Отбор',
            triagemDescription: 'Быстрая оценка вашего состояния здоровья',
            doacao: 'Пожертвование',
            doacaoDescription: 'Безопасный процесс под наблюдением профессионалов',
            lanche: 'Закуска',
            lancheDescription: 'Восстановите свою энергию с помощью специальной закуски',
            requisitosTitle: 'Требования к донорству',
            idade: 'Возраст',
            idadeDescription: 'От 16 до 69 лет',
            peso: 'Вес',
            pesoDescription: 'Минимум 50 кг',
            descanso: 'Отдых',
            descansoDescription: 'Хороший ночной сон',
            alimentacao: 'Питание',
            alimentacaoDescription: 'Не натощак',
            documentos: 'Документы',
            documentosDescription: 'Официальное удостоверение личности с фотографией',
            intervalo: 'Интервал',
            intervaloDescription: '60 дней для мужчин, 90 дней для женщин',
            agendamentoTitle: 'Запланируйте свое пожертвование',
            campanhasTitle: 'Активные кампании',
            precisamosDeO: 'Нам нужен O-',
            estoqueCritico: 'Критический запас! Ваше пожертвование необходимо.',
            campanhaEmpresarial: 'Корпоративная кампания',
            campanhaEmpresarialDescription: 'Ваша компания может изменить ситуацию! Организуйте кампанию по сбору пожертвований.',
            doeNoSeuAniversario: 'Пожертвуйте в свой день рождения',
            doeNoSeuAniversarioDescription: 'Отметьте свой день, спасая жизни! Получите специальный подарок.',
            contatoTitle: 'Свяжитесь с нами',
            telefone: 'Телефон',
            email: 'Электронная почта',
            enderecos: 'Адреса',
            envieSuaMensagem: 'Отправьте свое сообщение',
            bancoDeSangue: 'Банк крови',
            transformandoVidas: 'Изменение жизней через солидарность.',
            linksRapidos: 'Быстрые ссылки',
            horarioDeAtendimento: 'Часы работы',
            segundaASexta: 'С понедельника по пятницу: с 8:00 до 17:00',
            sabado: 'Суббота: с 8:00 до 12:00',
            domingo: 'Воскресенье: закрыто',
            newsletter: 'Новостная рассылка',
            recebaNovidades: 'Получайте новости и кампании',
            politicaDePrivacidade: 'Политика конфиденциальности',
            termosDeUso: 'Условия использования',
            mapaDoSite: 'Карта сайта',
            nomeLabel: 'Полное имя',
            nomePlaceholder: 'Имя',
            dataLabel: 'Предпочтительная дата',
            unidadeLabel: 'Единица сбора',
            selecioneUnidade: 'Выберите единицу',
            unidadeCentro: 'Центральный блок',
            unidadeZonaSul: 'Южная зона',
            unidadeZonaNorte: 'Северная зона',
            periodoLabel: 'Период',
            selecionePeriodo: 'Выберите период',
            periodoManha: 'Утро (8ч - 12ч)',
            periodoTarde: 'День (13ч - 17ч)',
            agendarBotao: 'Запланировать пожертвование',
            defaultResponse: 'Извините, я не понял ваш вопрос.'
        }
    };
});
